apiVersion: v1
kind: Secret
metadata:
  name: circlix-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  USER_DB_PASSWORD: "root"
  POST_DB_PASSWORD: "root"
  BID_DB_PASSWORD: "root"
  JWT_SECRET: "ThisIsASecretKeyWithAtLeast32Characters1234"
  TWILIO_ACCOUNT_SID: "ACb39602593d36a435c4f41981e3679cc4"
  TWILIO_AUTH_TOKEN: "27554d2b8a01d94f37c942a92acdf3e8"                #this will change for security purpose
  TWILIO_PHONE_NUMBER: "+18564153510"
